version: '3.8'

services:
  client:
    build: ./rpd-client-ts
    ports:
      - "8080:80"
    environment:
      - VITE_API_URL=http://89.169.130.200:8000
    networks:
      - app-network

  server:
    build: ./rpd-server
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - CLIENT_URL=http://89.169.130.200:8080
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=admin
      - DB_NAME=Rpd
      - DB_PORT=5432
      - ACCESS_TOKEN_SECRET=your_secret
      - REFRESH_TOKEN_SECRET=your_secret
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=Rpd
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: