version: '3.8'

services:
  db:
    image: postgres:12.20-alpine3.20
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: Rpd
    ports:
      - "5432:5432"
    networks:
      - dokploy-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 10s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rpd-server:
    build: .
    environment:
      PORT: 8000
      CLIENT_URL: http://localhost
      ACCESS_TOKEN_SECRET: access_abracadabra
      REFRESH_TOKEN_SECRET: refresh_abracadabra
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: admin
      DB_NAME: Rpd
      DB_PORT: 5432
    ports:
      - "8000:8000"
    networks:
      - dokploy-network
    depends_on:
      - db

  react-app:
    build: ../rpd-client-ts
    ports:
      - '80:80'
    networks:
      - dokploy-network

volumes:
  react_app:
  postgres_data:

networks:
  dokploy-network: